[google]
# Clave principal para autenticación simple
api_key = "AIzaSyA82YwMMkjSIBnevSXkEvfgPtA9VXcaeE8"

# Configuración de múltiples claves API para rotación
[[google.api_keys]]
key = "AIzaSyBVhWdlUeqXlxvf9Nldq-OId9Awoy4n1X4"
name = "mikel_main"

[[google.api_keys]]
key = "AIzaSyA82YwMMkjSIBnevSXkEvfgPtA9VXcaeE8"
name = "mikel_1"

[[google.api_keys]]
key = "AIzaSyDMqjrIBrLeTF8I2Rqp2M4aqS46zrCE3sI"
name = "mikel_otra"

[[google.api_keys]]
key = "AIzaSyBkpLD0fw-zFodOhRGnkF4bzQBYOzFu8d0"
name = "mikel_2"

[[google.api_keys]]
key = "AIzaSyAj0ppjyHkzmln9GQyPq6vRPGrncD9g3tE"
name = "mikel_3"

[[google.api_keys]]
key = "AIzaSyCiOU_-G44UGRJp4QP9trrXsWBO0GlTXPQ"
name = "mikel_4"

[[google.api_keys]]
key = "AIzaSyBT3yn5B42JT28fqKkA-kgDgVOfgJ3IOmM"
name = "frank_1"

[[google.api_keys]]
key = "AIzaSyBul84D3oblaj09308kOa-Ptb1Rh9XKHJo"
name = "frank_2"

[[google.api_keys]]
key = "AIzaSyALMtWMcZbBoUOoF3X1JFBN7visJrYH8cg"
name = "frank_3"